language: python
python:
- "3.6"
- "3.7"
- "3.8"
- "3.9"
env:
  global:
  - PIPENV_VENV_IN_PROJECT=1
  - PIPENV_IGNORE_VIRTUALENVS=1

# Install Dependencies
install: make dev

# Run Tests
script: make test
after_success: make coverage
